[package]
name = "petricor"
version = "0.1.0"
authors = ["lichtartig <sebschwieger@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-hashes = "0.9.0"
derive-new = "0.5"
secp256k1 = "0.19.0"